type Mutation {
  createMerchant(input: CreateMerchantInput!): Merchant!
  createReseller(input: CreateResellerInput!): Merchant!
  editMerchant(input: EditMerchantInput!):Merchant!
  editReseller(input: EditResellerInput!):Merchant!
}

type Query{
  getAllResellersByUser(userId:String!): [Merchant!]!
  getAllMerchantsByUser(userId:String!): [Merchant!]!
  getMerchantsByUser(userId:String!, merchantId:String): Merchant!
  getResellersByUser(userId:String!, resellerId:String): Merchant!
}


type Merchant {
  id: ID!
  userId: String!
  name: String!
  isReseller: Boolean!
  resellerId: String!
  phone: String!
  country: String!
  state: String!
  city: String!
  address: String!
  zipCode: String!
}

input CreateMerchantInput {
  userId: String!
  resellerId: String!
  isReseller: Boolean!
  name: String!
  phone: String!
  country: String!
  state: String!
  city: String!
  address: String!
  zipCode: String!
}

input EditMerchantInput{
  id: ID!
  userId: String!
  resellerId: String!
  name: String!
  phone: String!
  country: String!
  state: String!
  city: String!
  address: String!
  zipCode: String!
}

input EditResellerInput{
      id: ID!
      userId: String!
      name: String!
      phone: String!
      country: String!
      state: String!
      city: String!
      address: String!
      zipCode: String!
}


input CreateResellerInput {
  userId: String!
  isReseller: Boolean!
  name: String!
  phone: String!
  country: String!
  state: String!
  city: String!
  address: String!
  zipCode: String!
}
